--liquibase formatted sql
--changeset m_smirnov:person
create table if not exists persons
(
    id        bigint generated by default as identity primary key,
    sex       varchar(10)  not null,
    full_name varchar(255) not null
);
create table if not exists users
(
    id       bigint generated by default as identity primary key,
    name     varchar(255) not null,
    password varchar(255) not null
);
--rollback drop table persons;
--rollback drop table users;
