spring:
  liquibase:
    url: jdbc:postgresql://localhost:5432/m74-example-webflux
    user: campus
    password: campus
    change-log: classpath:db/changelog/db.changelog-master.yaml
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/m74-example-webflux
    username: campus
    password: campus
logging:
  level.org.springframework.r2dbc.core: DEBUG
