spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/example
    username: campus
    password: campus
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
logging:
  level.org.springframework.r2dbc.core: DEBUG
