create table if not exists users
(
    id        bigint generated by default as identity primary key,
    login     varchar(255) not null unique,
    full_name varchar(255) not null,
    password  varchar(255)
);